apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootsample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootsample
  template:
    metadata:
      labels:
        app: springbootsample
    spec:
      containers:
      - name: springbootsample
        image: amdp-registry.skala-ai.com/skala25a/sk081-spring-jenkins:1.0.0
        ports:
        - containerPort: 8080
